# Generated by Django 3.1 on 2020-08-18 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_subject_syllabus'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('syllabus', models.CharField(max_length=10)),
                ('Class', models.CharField(max_length=10)),
                ('sub1', models.CharField(blank=True, max_length=20)),
                ('sub2', models.CharField(blank=True, max_length=20)),
                ('sub3', models.CharField(blank=True, max_length=20)),
                ('sub4', models.CharField(blank=True, max_length=20)),
                ('sub5', models.CharField(blank=True, max_length=20)),
                ('sub6', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
