# Generated by Django 3.1 on 2020-08-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswersClass10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=50000, null=True)),
                ('image1', models.TextField(blank=True, null=True)),
                ('image2', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'answers_class10',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnswersCommerce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=50000, null=True)),
                ('image1', models.TextField(blank=True, null=True)),
                ('image2', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'answers_commerce',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnswersScience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=50000, null=True)),
                ('image1', models.TextField(blank=True, null=True)),
                ('image2', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'answers_science',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Class10',
            fields=[
                ('qid', models.IntegerField(primary_key=True, serialize=False)),
                ('qclass', models.IntegerField()),
                ('qno', models.IntegerField()),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('topic', models.CharField(blank=True, max_length=500, null=True)),
                ('question', models.CharField(blank=True, max_length=5000, null=True)),
                ('image1', models.TextField(blank=True, null=True)),
                ('image2', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'class10',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Commerce',
            fields=[
                ('qid', models.IntegerField(primary_key=True, serialize=False)),
                ('qclass', models.IntegerField()),
                ('qno', models.IntegerField()),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('topic', models.CharField(blank=True, max_length=500, null=True)),
                ('question', models.CharField(blank=True, max_length=5000, null=True)),
                ('image1', models.TextField(blank=True, null=True)),
                ('image2', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'commerce',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KnoxAuthtoken',
            fields=[
                ('digest', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('salt', models.CharField(max_length=16, unique=True)),
                ('created', models.DateTimeField()),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('token_key', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'knox_authtoken',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Science',
            fields=[
                ('qid', models.IntegerField(primary_key=True, serialize=False)),
                ('qclass', models.IntegerField()),
                ('qno', models.IntegerField()),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('topic', models.CharField(blank=True, max_length=500, null=True)),
                ('question', models.CharField(blank=True, max_length=5000, null=True)),
                ('image1', models.TextField(blank=True, null=True)),
                ('image2', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'science',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentsSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject1', models.CharField(max_length=25)),
                ('subject2', models.CharField(max_length=25)),
                ('subject3', models.CharField(max_length=25)),
                ('subject4', models.CharField(max_length=25)),
                ('subject5', models.CharField(max_length=25)),
                ('subject6', models.CharField(max_length=25)),
                ('syllabus_id', models.IntegerField()),
            ],
            options={
                'db_table': 'students_subject',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentsSyllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus', models.CharField(max_length=10)),
                ('classes', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'students_syllabus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
                ('email', models.CharField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'students_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentsUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
            ],
            options={
                'db_table': 'students_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentsUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'students_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YearClass10',
            fields=[
                ('qid', models.IntegerField(primary_key=True, serialize=False)),
                ('years', models.IntegerField()),
            ],
            options={
                'db_table': 'year_class10',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YearCommerce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'year_commerce',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YearScience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'year_science',
                'managed': False,
            },
        ),
    ]
