# Generated by Django 3.1 on 2020-08-19 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_answersclass10_answerscommerce_answersscience_authgroup_authgrouppermissions_authpermission_class10_'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profile_images'),
            preserve_default=False,
        ),
    ]
