# Generated by Django 3.1 on 2020-08-19 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20200819_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
