# Generated by Django 3.1 on 2020-08-19 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
