# Generated by Django 3.1 on 2020-08-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_auto_20200820_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='user',
        ),
    ]
