# Generated by Django 3.1 on 2020-08-20 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_auto_20200820_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.IntegerField(blank=True)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BookmarkQuest',
        ),
    ]
