# Generated by Django 3.1 on 2020-08-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0030_solvedquest_yearsub'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkquest',
            name='subject',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='bookmarkquest',
            name='year',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
