# Generated by Django 3.1 on 2020-08-25 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0032_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageClass10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='imagesClass10')),
                ('qid', models.ForeignKey(db_column='qid', on_delete=django.db.models.deletion.DO_NOTHING, to='students.class10')),
            ],
        ),
        migrations.CreateModel(
            name='ImageCommerce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='imagesCommerce')),
                ('qid', models.ForeignKey(db_column='qid', on_delete=django.db.models.deletion.DO_NOTHING, to='students.commerce')),
            ],
        ),
        migrations.CreateModel(
            name='ImageScience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='imagesScience')),
                ('qid', models.ForeignKey(db_column='qid', on_delete=django.db.models.deletion.DO_NOTHING, to='students.science')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
