# Generated by Django 3.1 on 2020-08-28 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0034_auto_20200828_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class10Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=50000, null=True)),
                ('image1', models.TextField(blank=True, null=True)),
                ('image2', models.TextField(blank=True, null=True)),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.class10')),
            ],
        ),
        migrations.DeleteModel(
            name='AnswerClass10',
        ),
    ]
