# Generated by Django 3.1 on 2020-08-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0037_auto_20200828_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class10answers',
            name='answer',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
