# Generated by Django 3.1 on 2020-08-28 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0039_auto_20200828_1111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswersClass10',
        ),
        migrations.DeleteModel(
            name='AnswersCommerce',
        ),
        migrations.DeleteModel(
            name='AnswersScience',
        ),
    ]
