# Generated by Django 3.1 on 2020-08-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0040_auto_20200828_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswersClass10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, max_length=10000, null=True)),
                ('image1', models.TextField(blank=True, null=True)),
                ('image2', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'answers_class10',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnswersCommerce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, max_length=10000, null=True)),
                ('image1', models.TextField(blank=True, null=True)),
                ('image2', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'answers_commerce',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnswersScience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, max_length=10000, null=True)),
                ('image1', models.TextField(blank=True, null=True)),
                ('image2', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'answers_science',
                'managed': False,
            },
        ),
    ]
