# Generated by Django 3.1 on 2020-08-28 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0042_auto_20200828_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class10Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, max_length=10000)),
                ('image1', models.ImageField(blank=True, upload_to='class10Answer')),
                ('image2', models.ImageField(blank=True, upload_to='class10Answer')),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.class10')),
            ],
        ),
    ]
