# Generated by Django 3.1 on 2020-08-28 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0043_class10answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScienceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, max_length=10000)),
                ('image1', models.ImageField(blank=True, upload_to='Science10Answer')),
                ('image2', models.ImageField(blank=True, upload_to='ScienceAnswer')),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.science')),
            ],
        ),
        migrations.CreateModel(
            name='CommerceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, max_length=10000)),
                ('image1', models.ImageField(blank=True, upload_to='CommerceAnswer')),
                ('image2', models.ImageField(blank=True, upload_to='CommerceAnswer')),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.commerce')),
            ],
        ),
    ]
