# Generated by Django 3.1 on 2020-08-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0044_commerceanswer_scienceanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='leftOff',
            fields=[
                ('qid', models.IntegerField(primary_key=True, serialize=False)),
                ('Subject', models.CharField(blank=True, max_length=50)),
                ('Year', models.IntegerField(blank=True)),
            ],
        ),
    ]
