# Generated by Django 3.1 on 2020-08-28 11:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0045_leftoff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leftoff',
            name='qid',
        ),
        migrations.AddField(
            model_name='leftoff',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.user'),
            preserve_default=False,
        ),
    ]
