# Generated by Django 3.1 on 2020-08-28 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0046_auto_20200828_1152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='leftOff',
        ),
    ]
