# Generated by Django 3.1 on 2020-08-28 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0047_delete_leftoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='leftWhere',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.user')),
                ('Subject', models.CharField(blank=True, max_length=50)),
                ('Year', models.IntegerField(blank=True)),
            ],
        ),
    ]
