# Generated by Django 3.1 on 2020-08-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0048_leftwhere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leftwhere',
            name='user',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
