# Generated by Django 3.1 on 2020-09-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0049_auto_20200828_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scienceanswer',
            name='image1',
            field=models.ImageField(blank=True, upload_to='Science12Answer'),
        ),
    ]
